### ISSUE TITLE
Fix busy background graphics

### ISSUE THREAD

**Issue by josiah1888** [josiah1888/game-dev#2]
The new background with the trees on the hill looks really busy. Since it has a similar color scheme as the foreground, it can be hard to tell what is interactive within the level and what is mere background.

Perhaps we adjust the opacity of the background image to make it seem more "in the background"?

**Comment by srsebastian1s** [comment]
Added capabilities to change background opacity in latest commit. It's set to 75% opacity right now. Adjust to desired levels if needed.
