### ISSUE TITLE
Soda Guy can throwing bugged

### ISSUE THREAD

**Issue by srsebastian1s** [josiah1888/game-dev#5]
The soda guys throw cans way faster than a new player could reasonably react, and, sometimes, soda guys do not throw cans at all (noticeable in level 7). Perhaps these issues are related to the can recycling feature, but I'm not sure.

**Comment by josiah1888** [comment]
In level seven, they weren't updating because they were being thrown out of bounds. That problem has been addressed now.

They are still throwing too fast though, that could be worked on

**Comment by srsebastian1s** [comment]
Hard-coded soda cans to slow down in latest commit. Not the most ideal solution, but only the soda can was bugged. Also ensured that the viewpoint does not scroll past the end of the level.

**Comment by josiah1888** [comment]
This just needs to be refactored, but it's not worth doing so the night before we present so we'll just let this issue sit for now

**Comment by josiah1888** [comment]
Refactored and readjusted in changeset fc7f689811daeb26b6c7cf502a73d94b7c7d962b
